### ISSUE TITLE
docker + yarn add ethstats-cli no longer works on node:latest

### ISSUE THREAD

**Issue by valer-cara** [Alethio/ethstats-cli#20]
#### Describe the bug
Proposed docker run command no longer seems to work with node:12 or node:13 (latest).

```
scrypt.target.mk:129: recipe for target 'Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o' failed
make: Leaving directory '/usr/local/share/.config/yarn/global/node_modules/scrypt/build'
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-50-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/share/.config/yarn/global/node_modules/scrypt
gyp ERR! node -v v12.13.0
```

#### To Reproduce
```
docker \
run -d \
--name ethstats-cli \
--restart always \
--net host \
-v /opt/ethstats-cli/:/root/.config/configstore/ \
node:latest \
/bin/sh -c "yarn global add ethstats-cli && ethstats-cli --register --account-email your@email.com --node-name your_node_name"
```
#### Expected behavior
ethstats-cli would start

#### Environment (please complete the following information):

 * OS name: Linux
 * Ethereum node name: none
 * Ethereum node version: none
 * ethstas-cli version: latest published npm

**Comment by valer-cara** [comment]
I've also noticed this intermitently on node:10.
I switched to using the `alethio/ethstats-cli` image in the end, went faster.
Maybe we should just update the docs and point to the official image instead.

**Comment by valer-cara** [comment]
Closing
